sudo: false
language: python
python:
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'

env:
  - TOXENV=packages
  - TOXENV=coverage
  - TOXENV=unittest

install:
  - pip install --upgrade --pre tox

script: tox --recreate

notifications:
  email:
    - efrain70@gmail.com

stages:
  - syntax
  - test
  - coveralls

jobs:
  include:
    - stage: syntax
      env: TOXENV:todo

    - stage: syntax
      env: TOXENV:flake8

    - stage: syntax
      env: TOXENV:code_complexity

    - stage: coveralls
      python: 3.6
      env: TOXENV=coveralls
