sudo: false
language: python
python:
  - '3.6'
  - '3.5'
  - '2.7'

env:
  - TOXENV=packages
  - TOXENV=coverage
  - TOXENV=unittest

install:
  - pip install --upgrade --pre tox

script: tox --recreate

notifications:
  email:
    - efrain70@gmail.com

stages:
  - syntax
  - test
  - coveralls

jobs:
  include:
    # - stage: syntax
    #  env: TOXENV=todo
    #  python: 3.6

    - stage: syntax
      env: TOXENV=flake8
      python: 3.6

    - stage: syntax
      env: TOXENV=code_complexity
      python: 3.6

    - stage: coveralls
      python: 3.6
      env: TOXENV=coveralls
