sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
env:
  - TOXENV=todo
  - TOXENV=flake8
  - TOXENV=code_complexity
  - TOXENV=packages
  - TOXENV=coverage
  - TOXENV=unittest

install:
  - pip install --upgrade --pre tox

script: tox --recreate

notifications:
  email:
    - efrain70@gmail.com

jobs:
  include:
    - stage: test
      env: TEXTENV=unittest
      python: 3.5

    - stage: test
      env: TEXTENV=unittest
      python: 3.6


    - stage: coveralls
      script: tox --recreate
      python: 3.6
      env: TEXTENV=coveralls
