sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
env:
  - TOXENV=packages
  - TOXENV=coverage

install:
  - pip install --upgrade --pre tox

script: tox --recreate

notifications:
  email:
    - efrain70@gmail.com

jobs:
  include:
    - stage: syntax
      env: TOXENV:todo
    - stage: syntax
      env: TOXENV:flake8
    - stage: syntax
      env: TOXENV:code_complexity

    - stage: test
      env: TOXENV=unittest
      python: 3.5

    - stage: test
      env: TOXENV=unittest
      python: 3.6

    - stage: coveralls
      script: tox --recreate
      python: 3.6
      env: TOXENV=coveralls
